### ISSUE TITLE
Package to be used with qt-pods

### ISSUE THREAD

**Issue by jacob3141** [VerbalExpressions/QtVerbalExpressions#1]
How cool is that? I would really miss it if it weren't packaged to be used with qt-pods.
See here for reference: https://github.com/cybercatalyst/qt-pods

**Comment by pathikrit** [comment]
Are you sure you posted in the right place or are you really grassrooting your library?

**Comment by jacob3141** [comment]
qt-pods is not a library. It is a package manager for libraries, so users can make use of your library in a standardized way. Similar to cocoapods for XCode on MacOS (in fact, it's inspired by that). I have experienced cocoapods from a user's perspective and I was astonished how good it works.

I thought we need that for Qt, too, so I made an attempt. Then I was searching for interesting Qt library projects on github and requested developers whether they would like to put their lib into the standardized format, so it can be used through the package manager.

If you think that's spammy, think about it again. I don't make a buck out of this, I just have work with it and want to give to the community. Also, because I am scratching a personal itch.

**Comment by pathikrit** [comment]
Ok feel free to send a pull request for this since we don't know much about qt-pods in here..

**Comment by jacob3141** [comment]
I have sent a pull request. Strictly speaking, the name of the repository should be qverbalexpressions to comply with the packaging rules. Also, the example code shouldn't be in, but I moved it to an example folder. I am always making a repository foo-example, where I pull in the pod and add one or more examples.

**Comment by jacob3141** [comment]
Ok, I added support and tested, works perfectly. Can be closed! :+1: :)
